name: X-FLoRA-asymmetirc-translation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - pillow
  - albumentations
  - torchmetrics
  - scikit-learn
  - umap-learn
  - pip:
    - brotli
    - albucore==0.0.17
    - annotated-types==0.7.0
    - asttokens==3.0.0
    - backcall==0.2.0
    - click==8.1.8
    - colorama==0.4.6
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.14
    - decorator==5.2.1
    - docker-pycreds==0.4.0
    - dominate==2.6.0
    - eval-type-backport==0.2.2
    - executing==2.2.0
    - filelock==3.16.1
    - fonttools==4.57.0
    - fsspec==2025.3.0
    - ftfy==6.2.3
    - gitdb==4.0.12
    - gitpython==3.1.44
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - ipykernel==6.29.5
    - ipython==8.12.3
    - jedi==0.19.2
    - jinja2==3.1.6
    - joblib==1.4.2
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lightning-utilities==0.11.9
    - llvmlite==0.41.1
    - markupsafe==2.1.5
    - mpmath==1.3.0
    - nest-asyncio==1.6.0
    - networkx==3.1
    - numba==0.58.1
    - openai-clip==1.0.1
    - opencv-python-headless==4.11.0.86
    - parso==0.8.4
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - promise==2.3
    - prompt-toolkit==3.0.50
    - protobuf==3.20.3
    - psutil==7.0.0
    - pure-eval==0.2.3
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pygments==2.19.1
    - pynndescent==0.5.13
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytorch-fid-wrapper==0.0.4
    - pytz==2025.2
    - pywavelets==1.4.1
    - pywin32==310
    - pyyaml==6.0.2
    - pyzmq==26.4.0
    - regex==2024.11.6
    - scikit-image==0.21.0
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.26.0
    - setproctitle==1.3.5
    - shortuuid==1.0.13
    - six==1.17.0
    - smmap==5.0.2
    - stack-data==0.6.3
    - sympy==1.13.3
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - torch==2.2.2+cu121
    - torchvision==0.17.2+cu121
    - torchaudio==2.2.2+cu121
    - -f https://download.pytorch.org/whl/torch_stable.html
    - torch-fidelity==0.3.0
    - torchfile==0.1.0
    - tornado==6.4.2
    - traitlets==5.14.3
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - visdom==0.1.8
    - wandb==0.12.18
    - wcwidth==0.2.13
    - websocket-client==1.8.0
    - zipp==3.20.2
